name: CTFO
favicon: null
layout_spectrum: 0.3102
typography_spectrum: 0.20501
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#62ff00'
    - '#774f1b'
    - '#e700fc'
    - '#dec300'
  brandStrength: 0.4375
  lightness: 0.6325676117558032
  saturation: 0.7340448570903391
  rhythmicContrast: 0.358434846624732
purpose: []
