name: CTFO
favicon: null
layout_spectrum: 0.2111234050244093
typography_spectrum: 0.05821605073288083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2839446587022394
  lightness: 0.6325676117558032
  saturation: 0.7340448570903391
  rhythmicContrast: 0.358434846624732
purpose: []
